import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import CarContextProvider from '@/context/car/provider'
import ConfigProvider from 'antd/lib/config-provider'
import theme from 'antd/lib/theme'
import Header from '@/components/common/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CarContextProvider>
          <Header />
          {children}
        </CarContextProvider>
      </body>
    </html>
  )
}
